<?php

/*
|--------------------------------------------------------------------------
| DO NOT EDIT THIS FILE! IT IS AUTO-GENERATED BY WEBSTUHL
|--------------------------------------------------------------------------
|
| Here we declare all of the Webstuhl resource routes.
|
|
*/

Route::resource('users', 'UserController');
Route::resource('loom_resources', 'LoomResourceController');
Route::resource('tests', 'TestController');
