<{{ '?' }}php

/*
|--------------------------------------------------------------------------
| DO NOT EDIT THIS FILE! IT IS AUTO-GENERATED BY WEBSTUHL
|--------------------------------------------------------------------------
|
| Here we declare all of the Webstuhl resource routes.
|
|
*/

@foreach (\App\Resources\WebstuhlResource::all() as $resource)
Route::resource('{{ $resource->url }}', '{{ str_replace(\Webstuhl::getResourceNamespace() . '\\', '', $resource->name) }}Controller');
@endforeach